#!/bin/bash

echo "Parsing..."
./bin/parse-table -conf etc/parse-table.conf -file tables/full-other.txt -segment_order=ascii,size_desc -placement_order=row,col -interpolate_type count -row_color_col -use_row_color_col -col_color_row -use_col_color_row -color_source row -transparency 1 -fade_transparency 0 -ribbon_layer_order=size_asc > data/parsed.txt
echo "Generating conf..."
cat data/parsed.txt | ./bin/make-conf -dir data
echo "Drawing Circos..."
../../bin/circos -conf etc/circos.conf | grep "created"
